### PR TITLE
Removing OTelRumConfig from initializer

### LINKED ISSUE #991: Enabling disk-buffering in the agent by default
This is a proposal to enable disk-buffering out of the box for the [agent initialization](https://github.com/open-telemetry/opentelemetry-android/blob/32fd8e1681dde7a0fc91381c047320bed0946c8e/android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt#L58). The agent initialization is supposed to contain all of our "opinions" on what parts of core/RUM should be enabled and how they should be configured so that the agent behaves well for most of the end-user use cases without having to write much code.

Storing signals on disk is crucial to avoid data loss, especially in mobile environments, so it makes sense to me that this feature should be enabled by default as part of the [agent initialization](https://github.com/open-telemetry/opentelemetry-android/blob/32fd8e1681dde7a0fc91381c047320bed0946c8e/android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt#L58). There might be reasons why disk buffering should be disabled in some cases, although my understanding is that those would be exceptional ones. Therefore, should we decide to enable it by default in the agent, we should include a config option to optionally disable it.

I'm looking forward to any opinions on this proposal before creating a PR to apply the changes to enable it by default, in case I missed something important that requires it to be kept disabled by default.

### PR DESCRIPTION
**Pull request by LikeTheSalad**
Related to #1257 
Closes #991

### CODE REVIEW

**Comment by fractalwrench** [comment]
Does #1273 cover everything that was previously possible to configure via `OtelRumConfig`, or are there some APIs that we're happy to jettison as part of this change?

**Comment by LikeTheSalad** [comment]
> Does #1273 cover everything that was previously possible to configure via `OtelRumConfig`, or are there some APIs that we're happy to jettison as part of this change?

The latter. My goal with these changes is to make the initializer API as lean as possible so that we can add stuff later as needed, and to minimize deprecations in the near future, in case some of the APIs we expose right away don't hold up to real-world use cases that people can find later. OtelRumConfig includes several low-level config options that I don't think it would be wise to release upfront, though some of them are needed for basic usage afaik, such as providing global attributes, which I think we can add via the initializer's parameters. Right now, I just added `globalAttributes` (and enabled disk buffering by default), though I'm open to adding any other config option from OtelRumConfig right now that someone else deems necessary for basic usage.

File: android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt [hunk 1]
```diff
@@ -72,13 +73,18 @@ object OpenTelemetryRumInitializer {
...
-        rumConfig: OtelRumConfig = OtelRumConfig(),
         sessionConfig: SessionConfig = SessionConfig.withDefaults(),
+        globalAttributes: (() -> Attributes)? = null,
         instrumentations: (InstrumentationConfiguration.() -> Unit)? = null,
     ): OpenTelemetryRum {
         instrumentations?.let { configure ->
             InstrumentationConfiguration().configure()
         }
+        val rumConfig = OtelRumConfig()
+        rumConfig.setDiskBufferingConfig(DiskBufferingConfig.create(enabled = true))
```
Comment (breedx-splk) [inline android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt]: At minimum, I think we need to expose a way to disable disk buffering and a way to turn on/off debugging for it (although that could be tied to a broader debug setting if one existed).

Comment (LikeTheSalad) [reply android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt]: Fair enough 👍 

I was thinking that it might be nice to reuse the same enabling/disabling config mechanism proposed for instrumentations [here](https://github.com/open-telemetry/opentelemetry-android/pull/1273) for diskbuffering as well. If you agree, then I'd like to hold this PR until that other one is merged, to do a rebase here and use the same config interface.

Comment (breedx-splk) [reply android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt]: Yeah, I like that approach and think it would apply nicely here too. If you would like to do it as a follow-up PR, please open a tracking issue so that we don't lose this. Otherwise, this PR should be good. ❤️

Comment (LikeTheSalad) [reply android-agent/src/main/kotlin/io/opentelemetry/android/agent/OpenTelemetryRumInitializer.kt]: Thank you. The changes aren't that much, so I've pushed them to this PR. I've added a DSL-like config for disk buffering that, for now, only allows enabling/disabling it, like so:

```kotlin
OpenTelemetryRumInitializer.initialize(
    diskBuffering = {
        enabled(false) // true by default
    }
)
```

Regarding the debug mode, in case we think it's helpful, I think it'd be better to have a broader debug setting. I was about to create an issue for it until I found [this one](https://github.com/open-telemetry/opentelemetry-android/issues/668), which I think is what we're looking for. FWIW, currently the debug mode for disk buffering means that some info level logs are only printed when debug = true, however, in my recent changes to disk buffering, I removed that flag and changed the log levels to a finer scope, which will make the logs only show up when the host app's JUL config is set to show those logs, which I guess will be when the app is running in "debug mode" in general, but it won't be the default. This change aligns disk buffering's logs with the rest of OTel Java related repos. If we wanted to provide a "debug mode", I think we need to decide what to do with all the OTel Java related repos' logs too, so it seems to me that this would require discussing it further, probably in a SIG meeting.

**Review by fractalwrench — APPROVED** [review]
LGTM

**Review by marandaneto — APPROVED** [review]
